trying out new script

diff --git a/inside-devbox b/inside-devbox
--- a/inside-devbox
+++ b/inside-devbox
@@ -1,13 +1,21 @@
-#!/usr/bin/env sh
-set -e
+#!/usr/bin/env bash
+set -euo pipefail
+
 cd ~
 
-# Packages
-sudo pacman -Syu --noconfirm
-sudo pacman -S emacs-wayland git nix ttf-jetbrains-mono direnv fish cmake --noconfirm
+# Validate arguments
+if [ "$#" -ne 1 ]; then
+    echo "Error: You did not supply enough arguments"
+    exit 1
+fi
+
+# Symlinks
+ln -s "$1/.config/emacs" .emacs.d
+ln -s "$1/.ssh" .ssh
+ln -s "$1/.config/git/config" .gitconfig
 
 # Fish
-sudo usermod --shell /usr/bin/fish $USER
+sudo usermod --shell /usr/bin/fish "$USER"
 mkdir -p .config/fish
 
 # Nix
@@ -28,7 +36,5 @@ end
 # Direnv
 echo 'direnv hook fish | source' >> .config/fish/config.fish
 
-# Symlinks
-ln -s /home/aiyaz/.config/emacs .emacs.d
-ln -s /home/aiyaz/.ssh .ssh
-ln -s /home/aiyaz/.config/git/config .gitconfig
+# Emacs
+distrobox-export --app emacs
